### ISSUE TITLE
Release request?

### ISSUE THREAD

**Issue by proycon** [Orange-OpenSource/pn#3]
We are using pn as a component in [Sxmo](https://sxmo.org) and have packaged it for Alpine Linux. For the packaging effort in Linux distributions like Alpine, it would help if you could release pn with a version number using Github's release mechanism (and the appropriate git tag)?

Thanks!

**Comment by camilleoudot** [comment]
Hi,

Thanks for your interest in pn, I'll definitely look into this if it is useful. What is the minimum requirement? Is a git tag with the version enough? And beyond the minimum viable feature, what's the ideal target ?

**Comment by camilleoudot** [comment]
I've created the release v0.9.0: https://github.com/Orange-OpenSource/pn/releases/tag/v0.9.0

Does it solve the issue?

**Comment by proycon** [comment]
Yes, perfect! Thank you!
